language: cpp
before_script:

script:
- cmake .
- cmake --build .
- cmake --build . --target package

after_success:
- sudo apt-get install doxygen graphviz
- ./publish-doxygen

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uyhwh:$BINTRAY_API_KEY "https://api.bintray.com/content/yhwh/otus/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"